/**
 * Shared component exports
 */

export { Layout } from './Layout'
export { Header } from './Header'
export { Sidebar } from './Sidebar'
export { ErrorBoundary } from './ErrorBoundary'
export { TabButton } from './TabButton'
export { EmptyState } from './EmptyState'
export { StatCard } from './StatCard'
export { PersonCard } from './PersonCard'
export { SectionHeader } from './SectionHeader'
export { ActivityItem } from './ActivityItem'
export { ModalWrapper } from './ModalWrapper'
export { BadgeGroup } from './BadgeGroup'
export { SkeletonCard } from './SkeletonCard'
export { SkeletonGrid } from './SkeletonGrid'
export { RepoLink, RepoLinkOrSuggest } from './RepoLink'
export { BeforeAfterSlider } from './BeforeAfterSlider'
export { CopyFeedbackToast } from './CopyFeedbackToast'

export type { EmptyStateAction, EmptyStateProps } from './EmptyState'
export type { StatCardProps } from './StatCard'
export type { PersonCardProfile, PersonCardProps } from './PersonCard'
export type { SectionHeaderAction, SectionHeaderProps } from './SectionHeader'
export type { ActivityItemProps, ActivityItemType } from './ActivityItem'
export type { ModalWrapperProps } from './ModalWrapper'
export type { BadgeGroupBadge, BadgeGroupProps, BadgeVariant } from './BadgeGroup'
export type { SkeletonCardProps } from './SkeletonCard'
export type { SkeletonGridProps } from './SkeletonGrid'
export type { RepoLinkProps, RepoLinkOrSuggestProps, SourceRepo, RepoPlatform } from './RepoLink'